### ISSUE TITLE
finetune.py

### ISSUE THREAD

**Issue by YomnaEid** [rravipra/CSE-493#1]
Thanks for your great work!

I have a question regarding the finetune.py file where you were using BERT, could you explain it as BERT was not mentioned in your Medium article and I am confused about this file.

Thanks.

**Comment by rravipra** [comment]
Hi,

Thanks for reaching out! Please refer to LLM_FineTuning_Research.ipynb since that is what we ended up using for our final model, we initially thought of using BERT but later realized that GPT-2 would be the best model for our purpose. The finetune.py file was the initial model that we tried to consider but ended up **not** using it for our experimentation and inference. I just added that file in case someone else wants to reproduce it and experiment it using BERT. I hope that answers your question!
